recipe: default.v1
assistant_id: 20260203-143334-fresh-squib
language: en

pipeline:
    # loads spacy
  - name: SpacyNLP
    model: "en_core_web_lg" 
    # tokenizes with spacy
  - name: SpacyTokenizer
    # creates feature vectors using spacy's pre-trained ones
  - name: SpacyFeaturizer
    pooling: "mean"  
    # improves feature vectors by averaging token vectors and looking at the overall sentence structure
  - name: LexicalSyntacticFeaturizer
    # counts word n-grams to capture specific phrases and patterns
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 3  
    # counts character n-grams to capture patterns and eventual mispellings
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 2 
    max_ngram: 5 
    # uses regex patterns to compute intent hints
  - name: RegexFeaturizer
    case_sensitive: false
    # predicts intents 
  - name: DIETClassifier
    epochs: 250  
    constrain_similarities: true  
    embedding_dimension: 128 
    number_of_transformer_layers: 2 
    transformer_size: 128  
    drop_rate: 0.25  
    weight_sparsity: 0.7  
    evaluate_every_number_of_epochs: 10  
    evaluate_on_number_of_examples: 50 
    loss_type: "cross_entropy" 
    similarity_type: "inner" 
    use_sparse_input_dropout: true 
    sparse_input_dropout_rate: 0.1 
    use_key_relative_attention: true 
    key_relative_attention_num_heads: 4  
    # fallback classifier to handle low-confidence predictions
  - name: FallbackClassifier
    threshold: 0.75 

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3 